name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ nodejs python3

      - name: Run tests
        run: python3 test_runner/main.py

      - name: Upload test results artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/results.json

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: results

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
